@startuml
'left to right direction

title WebHooks Microservice activity

start

while (Cancelation Requested?) is (false)


fork
    :Sourcing Events();

    if (New event?) then (true)
        partition #PaleGreen Database {
            :fetchSubscriptions();
            while (Next?) is (true)
            :createPayLoad(event, subscription);
            endwhile (false)
        }
        #pink :break;
    else (false)
        #pink :break;
    endif


fork again
    :Delivering Payloads();
    if (Peek Payload?) then (true)
        partition #PaleGreen Queue {

            repeat :DelevirerPayload()

            split
                :Thread #1;
                split again
                :Thread #N;
            end split

            backward : Attempts Counter ++;
            note right: Notify Retrier

            repeat while (Success?) is (false) not (true)
        }
    else (false)
        #pink :break;
    endif

end fork

endwhile (true)

stop



@enduml
